export { isArray, notArray } from '@/array'
export { isBoolean, notBoolean } from '@/boolean'
export { Empty, isEmpty, notEmpty } from '@/empty'
export { isFunction, notFunction } from '@/function'
export { Integer, isInteger, notInteger } from '@/integer'
export { is, isBasic, isType, not, notBasic, notType } from '@/is'
export { Null, isNull, notNull } from '@/null'
export { isNumber, notNumber } from '@/number'
export { isObject, notObject } from '@/object'
export { isString, notString } from '@/string'
export { Undefined, isUndefined, notUndefined } from '@/undefined'
